server:
  port: 8080

spring:
  application:
    name: webrisetest
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5433/webrise
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect